spring:
  application:
    name: cdmsa

  autoconfigure:
    exclude:
      - org.springframework.ai.model.openai.autoconfigure.OpenAiEmbeddingAutoConfiguration
      - org.springframework.ai.model.azure.openai.autoconfigure.AzureOpenAiChatAutoConfiguration

  ai:
    openai:
      api-key: "openrouter key"
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: mistralai/mistral-7b-instruct:free

    azure:
      openai:
        api-key: "azure key"
        endpoint: "azure endpoint"
        embedding:
          options:
            deployment-name: text-embedding-3-small

    vectorstore:
      pgvector:
        # Create table vector_store
        initialize-schema: true
        index-type: HNSW
        # Model dimension
        dimension: 1536
        distance-type: COSINE_DISTANCE


server:
  port: 8080